## Deliverable 2. Create a Customer Travel Destinations Map.

In [20]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps 
import numpy as np

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [21]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Mount Isa,AU,-20.7333,139.5000,62.37,27,0,16.11,clear sky
1,1,Nikolskoye,RU,59.7035,30.7861,63.81,98,19,4.76,few clouds
2,2,Srednekolymsk,RU,67.4500,153.6833,76.26,44,100,8.48,overcast clouds
3,3,Bluff,NZ,-46.6000,168.3333,44.80,92,100,22.35,moderate rain
4,4,Port Lincoln,AU,-34.7333,135.8667,56.64,61,100,8.50,overcast clouds

In [22]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

In [23]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & (city_data_df["Max Temp"] >= min_temp)]

In [24]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

Unnamed: 0             387
City                   387
Country                387
Lat                    387
Lng                    387
Max Temp               387
Humidity               387
Cloudiness             387
Wind Speed             387
Current Description    387
dtype: int64

In [25]:
# 4b. Drop any empty rows and create a new DataFrame that doesnâ€™t have empty rows.
clean_df = preferred_cities_df.dropna()

In [26]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Srednekolymsk,RU,76.26,overcast clouds,67.4500,153.6833,
5,Arraial Do Cabo,BR,71.46,broken clouds,-22.9661,-42.0278,
10,Kapaa,US,84.52,few clouds,22.0752,-159.3190,
11,Kushmurun,KZ,67.26,broken clouds,52.4503,64.6311,
12,Rikitea,PF,75.13,few clouds,-23.1203,-134.9692,
13,Lata,PT,76.08,overcast clouds,40.1629,-8.3327,
15,Flin Flon,CA,77.79,broken clouds,54.7682,-101.8650,
16,Vaini,TO,80.76,few clouds,-21.2000,-175.2000,
18,Myaundzha,RU,71.89,light rain,63.0494,147.1858,
20,Jega,NG,79.02,light rain,12.2175,4.3792,

In [27]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
    params["location"] = f"{lat},{lng}"

    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()

    # print(hotels["results"][0]["name"])
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
       
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [28]:
hotel_df.replace("", np.NaN, inplace=True)
hotel_df.head(10)

#hotel_df.dropna(subset = ["column2"], inplace=True)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Srednekolymsk,RU,76.26,overcast clouds,67.4500,153.6833,NaN
5,Arraial Do Cabo,BR,71.46,broken clouds,-22.9661,-42.0278,Pousada Porto Praia
10,Kapaa,US,84.52,few clouds,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
11,Kushmurun,KZ,67.26,broken clouds,52.4503,64.6311,Gostinitsa Pri Depo
12,Rikitea,PF,75.13,few clouds,-23.1203,-134.9692,People ThankYou
13,Lata,PT,76.08,overcast clouds,40.1629,-8.3327,Casa Maquia
15,Flin Flon,CA,77.79,broken clouds,54.7682,-101.8650,Victoria Inn Flin Flon
16,Vaini,TO,80.76,few clouds,-21.2000,-175.2000,Keleti Beach Resort
18,Myaundzha,RU,71.89,light rain,63.0494,147.1858,NaN
20,Jega,NG,79.02,light rain,12.2175,4.3792,ALH. Nasiru Ibrahim

In [29]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna()
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
5,Arraial Do Cabo,BR,71.46,broken clouds,-22.9661,-42.0278,Pousada Porto Praia
10,Kapaa,US,84.52,few clouds,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
11,Kushmurun,KZ,67.26,broken clouds,52.4503,64.6311,Gostinitsa Pri Depo
12,Rikitea,PF,75.13,few clouds,-23.1203,-134.9692,People ThankYou
13,Lata,PT,76.08,overcast clouds,40.1629,-8.3327,Casa Maquia
15,Flin Flon,CA,77.79,broken clouds,54.7682,-101.8650,Victoria Inn Flin Flon
16,Vaini,TO,80.76,few clouds,-21.2000,-175.2000,Keleti Beach Resort
20,Jega,NG,79.02,light rain,12.2175,4.3792,ALH. Nasiru Ibrahim
23,Faanui,PF,78.76,clear sky,-16.4833,-151.7500,Bora-Bora Pearl Beach Resort & Spa
24,Lagoa,PT,69.04,overcast clouds,39.0500,-27.9833,Casa Das Faias

In [30]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [31]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# !!!!!!! CHECK !!!!!!!!!
# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = pd.DataFrame(clean_hotel_df[["Lat", "Lng"]])

In [33]:
# 11a. Add a marker layer for each city to the map. 
locations = locations 
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))